// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BsModalController from "./bs_modal_controller"
application.register("bs-modal", BsModalController)

import EditUserDescriptionController from "./edit_user_description_controller"
application.register("edit-user-description", EditUserDescriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserNameController from "./user_name_controller"
application.register("user-name", UserNameController)
